### ISSUE TITLE
Missing README.md in tarball on PyPI

### ISSUE THREAD

**Issue by dandye** [benjamin9999/pydux#9]
The [tarball on PyPI for version 0.2.0](https://pypi.python.org/packages/de/41/dad439e886df8865b76f4619dc141a932a5fbdad9045d6ba393126f43bdf/pydux-0.2.0.tar.gz#md5=7560c950d6223330bd266e994e9aa67f
) is missing the README.md file, which causes `pip install` to fail:
```
Collecting pydux>=0.1.0 (from urwid_pydux==0.2.0->-r ./edge_vm_installer/requirements.txt (line 4))
  Downloading pydux-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ESMAa7/pydux/setup.py", line 17, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by usrlocalben** [comment]
fixed with 846dd7e38d954a6a86b1e01e0ea1a423423844f0
